spring:
  profiles:
    active: test
---
server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.abc.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#spring配置
spring:
  profiles: dev
  application:
    name: springcloud-config-dept  # 3个服务名称相同 是前提条件
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

# Eureka的配置  服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001 #修改eureka上的默认描述信息
    prefer-ip-address: true # true 可以现实IP地址

#
info:
  app.name: andy-springcloud
  company.name: blog.andy.com
  

---
server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.abc.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#spring配置
spring:
  profiles: test
  application:
    name: springcloud-config-dept  # 3个服务名称相同 是前提条件
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db03?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

# Eureka的配置  服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001 #修改eureka上的默认描述信息
    prefer-ip-address: true # true 可以现实IP地址

#
info:
  app.name: andy-springcloud
  company.name: blog.andy.com
